joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01

servos:
  pwm_frequency: 50
  throttle:
    channel: 0
    center: 320
    direction: 1
    range: 100
  steering:
    channel: 11
    center: 325
    direction: 1
    range: 160

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: servos_drive
    axis_mappings:
      - axis: 1
        target: linear.x
        scale: 1.0
      - axis: 2
        target: angular.z
        scale: 1.0