joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01

servos:
  pwm_frequency: 50
  absolute_topic: /servo_absolute
  twist_topic: /autopilot/drive
  throttle:
    channel: 0
    center: 320
    direction: 1
    range: 120
  steering:
    channel: 11
    center: 325
    direction: 1
    range: 160

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /manual/drive
    axis_mappings:
      - axis: 1
        target: linear.x
        scale: 0.6
      - axis: 2
        target: angular.z
        scale: 0.6
  start_recording:
    type: service
    service_name: /recording
    service_request:
      status: True
    buttons: [2]
  stop_recording:
    type: service
    service_name: /recording
    service_request:
      status: False
    buttons: [1]

ina219:
  device: "/dev/i2c-1"
  address: 68
  rshunt: 0.1
  calibration: 4096
  # POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0
  # POWER_SUPPLY_TECHNOLOGY_NIMH = 1
  # POWER_SUPPLY_TECHNOLOGY_LION = 2
  # POWER_SUPPLY_TECHNOLOGY_LIPO = 3
  # POWER_SUPPLY_TECHNOLOGY_LIFE = 4
  # POWER_SUPPLY_TECHNOLOGY_NICD = 5
  # POWER_SUPPLY_TECHNOLOGY_LIMN = 6
  technology: 3
  capacity: 2200
  cells: 2

trainer:
  camera_topic: /camera/image_raw
  manual_twist_topic: /servos_drive
  storage: /home/jetracer/training
  sample_interval: 125
  throttle_threshold: 0.05

autopilot:
  camera_topic: /camera/image_raw
  manual_twist_topic: /manual/drive
  control_interval: 100.0
  throttle_threshold: 0.05
  model: "/home/jetracer/notebook/2019-09-29T140313.637906_2_trt.pth"
  published_twist: /autopilot/drive
