joy_node:
  auto_repeat_rate: 30
  coalesce_interval: 0.0333
  deadzone: 0.01

servos:
  pwm_frequency: 50
  throttle:
    channel: 0
    center: 320
    direction: 1
    range: 120
  steering:
    channel: 11
    center: 325
    direction: 1
    range: 180

teleop:
  drive:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: servos_drive
    axis_mappings:
      - axis: 1
        target: linear.x
        scale: 1.0
      - axis: 2
        target: angular.z
        scale: 1.0
  start_recording:
    type: service
    service_name: /recording
    service_request:
      status: True
    buttons: [2]
  stop_recording:
    type: service
    service_name: /recording
    service_request:
      status: False
    buttons: [1]

ina219:
  device: "/dev/i2c-1"
  address: 68
  publish_voltage_bus: true
  publish_power: true
  rshunt: 0.1
  calibration: 4096
trainer:
  camera_topic: /camera/image_raw
  manual_twist_topic: /servos_drive
  storage: /home/jetracer/training